services:
  backend:
    container_name: backend
    build:
      context: ./backend
    networks:
      - react-express
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    networks:
      - react-express
    depends_on:
      - backend
    ports:
      - 8080:8080
networks:
  react-express:
    driver: bridge
