services:
  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express
    depends_on:
      - backend
    ports:
      - 5000:5000
networks:
  react-express:
    driver: bridge